#!/bin/csh
# limit coredumpsize 0
cd /home/wolf/BUU/buu2012
# set OUTFILE=pp_35.out
set OUTFILE=/dev/null
set INFILE=readin/pp_35.in
cat job_pp35 > $OUTFILE
cat $INFILE >> $OUTFILE
buusrcnew/BUU.x < $INFILE >> $OUTFILE
