#!/bin/bash
# limit coredumpsize 0
# cd /home/gwolf/BUU/buu2018
OUTFILE=pbarAu06b02d_JPsi_mat.out
# set OUTFILE=/dev/null
INFILE=readin/pbarAu06b02d_JPsi_mat.in
cat job_pbarAu06b02d_JPsi_mat > $OUTFILE
cat $INFILE >> $OUTFILE
buusrc0/BUU.x < $INFILE >> $OUTFILE
